-- FWK_BATCH_HIS definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_BATCH_HIS;

CREATE TABLE FWK_BATCH_HIS (
	BATCH_APP_ID VARCHAR(50),
	INSTANCE_ID VARCHAR(4),
	BATCH_DATE VARCHAR(8),
	BATCH_EXECUTE_SEQ DECIMAL(3,0) DEFAULT 1 ,
	LOG_DTIME VARCHAR(17) DEFAULT NULL ,
	BATCH_END_DTIME VARCHAR(17) DEFAULT NULL,
	RES_RT_CODE VARCHAR(40),
	LAST_UPDATE_USER_ID VARCHAR(20),
	ERROR_CODE VARCHAR(40),
	ERROR_REASON VARCHAR(4000),
	RECORD_COUNT DECIMAL(10,0),
	EXECUTE_COUNT DECIMAL(10,0),
	SUCCESS_COUNT DECIMAL(10,0),
	FAIL_COUNT DECIMAL(10,0),
	CONSTRAINT PK_FWK_BATCH_HIS PRIMARY KEY (BATCH_APP_ID,INSTANCE_ID,BATCH_DATE,BATCH_EXECUTE_SEQ),
	CONSTRAINT SYS_C0011099 CHECK (BATCH_APP_ID IS NOT NULL),
	CONSTRAINT SYS_C0011100 CHECK (INSTANCE_ID IS NOT NULL),
	CONSTRAINT SYS_C0011101 CHECK (BATCH_DATE IS NOT NULL),
	CONSTRAINT SYS_C0011102 CHECK (BATCH_EXECUTE_SEQ IS NOT NULL),
	CONSTRAINT SYS_C0011103 CHECK (LOG_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0011104 CHECK (LAST_UPDATE_USER_ID IS NOT NULL)
);
