-- FWK_USER_MENU definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_USER_MENU;

CREATE TABLE FWK_USER_MENU (
	USER_ID VARCHAR(20),
	MENU_ID VARCHAR(40),
	AUTH_CODE VARCHAR(1),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	FAVOR_MENU_ORDER DECIMAL(3,0) DEFAULT 0 ,
	CONSTRAINT PK_FWK_USER_MENU PRIMARY KEY (USER_ID,MENU_ID),
	CONSTRAINT SYS_C0012777 CHECK (USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0012778 CHECK (MENU_ID IS NOT NULL),
	CONSTRAINT SYS_C0012779 CHECK (AUTH_CODE IS NOT NULL),
	CONSTRAINT SYS_C0012780 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0012781 CHECK (LAST_UPDATE_USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0012782 CHECK (FAVOR_MENU_ORDER IS NOT NULL)
);
