-- FWK_LISTENER_TRX_MESSAGE definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_LISTENER_TRX_MESSAGE;

CREATE TABLE FWK_LISTENER_TRX_MESSAGE (
	GW_ID VARCHAR(20),
	REQ_ID_CODE VARCHAR(40),
	TRX_ID VARCHAR(40),
	ORG_ID VARCHAR(10),
	IO_TYPE VARCHAR(1),
	BIZ_APP_ID VARCHAR(100),
	CONSTRAINT PK_FWK_LISTENER_TRX_MESSAGE PRIMARY KEY (GW_ID,REQ_ID_CODE),
	CONSTRAINT SYS_C0012252 CHECK (GW_ID IS NOT NULL),
	CONSTRAINT SYS_C0012253 CHECK (REQ_ID_CODE IS NOT NULL)
);
