-- FWK_CODE definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_CODE;

CREATE TABLE FWK_CODE (
	CODE_GROUP_ID VARCHAR(8),
	CODE VARCHAR(50),
	CODE_NAME VARCHAR(100),
	CODE_DESC VARCHAR(200),
	SORT_ORDER DECIMAL(4,0) DEFAULT 0 ,
	USE_YN VARCHAR(1) DEFAULT 'Y' ,
	CODE_ENGNAME VARCHAR(300),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL,
	LAST_UPDATE_USER_ID VARCHAR(20),
	FINAL_APPROVAL_STATE VARCHAR(1),
	FINAL_APPROVAL_DTIME VARCHAR(14),
	FINAL_APPROVAL_USER_ID VARCHAR(20),
	FINAL_APPROVAL_USER_NAME VARCHAR(50),
	CONSTRAINT PK_FWK_CODE PRIMARY KEY (CODE_GROUP_ID,CODE),
	CONSTRAINT SYS_C0011202 CHECK (CODE_GROUP_ID IS NOT NULL),
	CONSTRAINT SYS_C0011203 CHECK (CODE IS NOT NULL),
	CONSTRAINT SYS_C0011204 CHECK (CODE_NAME IS NOT NULL),
	CONSTRAINT SYS_C0011205 CHECK (SORT_ORDER IS NOT NULL),
	CONSTRAINT SYS_C0011206 CHECK (USE_YN IS NOT NULL)
);
