-- FWK_MESSAGE_FIELD_HISTORY definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_MESSAGE_FIELD_HISTORY;

CREATE TABLE FWK_MESSAGE_FIELD_HISTORY (
	ORG_ID VARCHAR(10),
	MESSAGE_ID VARCHAR(50),
	MESSAGE_FIELD_ID VARCHAR(50),
	VERSION DECIMAL(3,0),
	SORT_ORDER DECIMAL(4,0) DEFAULT 0 ,
	DATA_TYPE VARCHAR(1),
	DATA_LENGTH BIGINT,
	`SCALE` DECIMAL(2,0),
	ALIGN VARCHAR(1),
	FILLER VARCHAR(20),
	FIELD_TYPE VARCHAR(10),
	USE_MODE VARCHAR(20),
	REQUIRED_YN VARCHAR(1) DEFAULT 'Y',
	FIELD_TAG VARCHAR(500),
	CODE_GROUP VARCHAR(8),
	DEFAULT_VALUE VARCHAR(500),
	TEST_VALUE VARCHAR(500),
	REMARK VARCHAR(1) DEFAULT NULL,
	LOG_YN VARCHAR(1) DEFAULT 'Y',
	CODE_MAPPING_YN VARCHAR(1) DEFAULT 'N',
	MESSAGE_FIELD_NAME VARCHAR(100),
	MESSAGE_FIELD_DESC VARCHAR(200),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	VALIDATION_RULE_ID VARCHAR(20),
	LAST_UPDATE_USER_ID VARCHAR(20),
	CONSTRAINT PK_FWK_MESSAGE_FIELD_HISTORY PRIMARY KEY (ORG_ID,MESSAGE_ID,MESSAGE_FIELD_ID,VERSION),
	CONSTRAINT SYS_C0012977 CHECK (DATA_LENGTH IS NOT NULL),
	CONSTRAINT SYS_C0014813 CHECK (ORG_ID IS NOT NULL),
	CONSTRAINT SYS_C0014814 CHECK (MESSAGE_ID IS NOT NULL),
	CONSTRAINT SYS_C0014815 CHECK (MESSAGE_FIELD_ID IS NOT NULL),
	CONSTRAINT SYS_C0014816 CHECK (VERSION IS NOT NULL),
	CONSTRAINT SYS_C0014817 CHECK (SORT_ORDER IS NOT NULL),
	CONSTRAINT SYS_C0014818 CHECK (DATA_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0014819 CHECK (ALIGN IS NOT NULL),
	CONSTRAINT SYS_C0014833 CHECK (LAST_UPDATE_DTIME IS NOT NULL)
);
