-- FWK_MONITOR definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_MONITOR;

CREATE TABLE FWK_MONITOR (
	MONITOR_ID VARCHAR(20),
	MONITOR_NAME VARCHAR(50),
	MONITOR_QUERY VARCHAR(2000),
	ALERT_CONDITION VARCHAR(100),
	ALERT_MESSAGE VARCHAR(100),
	REFRESH_TERM VARCHAR(4),
	DETAIL_QUERY VARCHAR(2000),
	USE_YN VARCHAR(1) DEFAULT 'Y',
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	CONSTRAINT PK_FWK_MONITOR PRIMARY KEY (MONITOR_ID),
	CONSTRAINT SYS_C0012288 CHECK (MONITOR_ID IS NOT NULL),
	CONSTRAINT SYS_C0012289 CHECK (MONITOR_NAME IS NOT NULL),
	CONSTRAINT SYS_C0012290 CHECK (REFRESH_TERM IS NOT NULL),
	CONSTRAINT SYS_C0012291 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0012292 CHECK (LAST_UPDATE_USER_ID IS NOT NULL)
);
