-- FWK_MENU definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_MENU;

CREATE TABLE FWK_MENU (
	MENU_ID VARCHAR(40),
	PRIOR_MENU_ID VARCHAR(40),
	SORT_ORDER DECIMAL(3,0) DEFAULT 0 ,
	MENU_NAME VARCHAR(100),
	MENU_URL VARCHAR(200),
	MENU_IMAGE VARCHAR(50),
	DISPLAY_YN VARCHAR(1) DEFAULT 'Y' ,
	USE_YN VARCHAR(1) DEFAULT 'Y' ,
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	WEB_APP_ID VARCHAR(70),
	MENU_ENG_NAME VARCHAR(200),
	CONSTRAINT PK_FWK_MENU PRIMARY KEY (MENU_ID),
	CONSTRAINT SYS_C0012263 CHECK (MENU_ID IS NOT NULL),
	CONSTRAINT SYS_C0012264 CHECK (PRIOR_MENU_ID IS NOT NULL),
	CONSTRAINT SYS_C0012265 CHECK (SORT_ORDER IS NOT NULL),
	CONSTRAINT SYS_C0012266 CHECK (MENU_NAME IS NOT NULL),
	CONSTRAINT SYS_C0012267 CHECK (MENU_URL IS NOT NULL),
	CONSTRAINT SYS_C0012268 CHECK (DISPLAY_YN IS NOT NULL),
	CONSTRAINT SYS_C0012269 CHECK (USE_YN IS NOT NULL),
	CONSTRAINT SYS_C0012270 CHECK (LAST_UPDATE_DTIME IS NOT NULL)
);
