-- FWK_ROLE definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_ROLE;

CREATE TABLE FWK_ROLE (
	ROLE_ID VARCHAR(10),
	ROLE_NAME VARCHAR(50),
	USE_YN VARCHAR(1) DEFAULT 'Y',
	ROLE_DESC VARCHAR(200),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	RANKING VARCHAR(100),
	FINAL_APPROVAL_STATE VARCHAR(1),
	FINAL_APPROVAL_DTIME VARCHAR(14),
	FINAL_APPROVAL_USER_ID VARCHAR(20),
	FINAL_APPROVAL_USER_NAME VARCHAR(50),
	CONSTRAINT PK_FWK_ROLE PRIMARY KEY (ROLE_ID),
	CONSTRAINT SYS_C0012392 CHECK (ROLE_ID IS NOT NULL),
	CONSTRAINT SYS_C0012393 CHECK (ROLE_NAME IS NOT NULL),
	CONSTRAINT SYS_C0012394 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0012395 CHECK (LAST_UPDATE_USER_ID IS NOT NULL)
);
