-- FWK_BOARD definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_BOARD;

CREATE TABLE FWK_BOARD (
	BOARD_ID VARCHAR(20),
	BOARD_NAME VARCHAR(50),
	BOARD_TYPE VARCHAR(1),
	ADMIN_ID VARCHAR(20),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	CONSTRAINT SYS_C0011121 CHECK (BOARD_ID IS NOT NULL),
	CONSTRAINT SYS_C0011122 CHECK (BOARD_NAME IS NOT NULL),
	CONSTRAINT SYS_C0011123 CHECK (BOARD_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0011124 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0011125 CHECK (LAST_UPDATE_USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0011126 PRIMARY KEY (BOARD_ID)
);
