-- FWK_ORG definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_ORG;

CREATE TABLE FWK_ORG (
	ORG_ID VARCHAR(10),
	ORG_NAME VARCHAR(50),
	ORG_DESC VARCHAR(200),
	START_TIME VARCHAR(6),
	END_TIME VARCHAR(6),
	XML_ROOT_TAG VARCHAR(20),
	CONSTRAINT PK_FWK_ORG PRIMARY KEY (ORG_ID),
	CONSTRAINT SYS_C0012313 CHECK (ORG_ID IS NOT NULL),
	CONSTRAINT SYS_C0012314 CHECK (ORG_NAME IS NOT NULL),
	CONSTRAINT SYS_C0012315 CHECK (START_TIME IS NOT NULL),
	CONSTRAINT SYS_C0012316 CHECK (END_TIME IS NOT NULL)
);
