-- FWK_SERVICE definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_SERVICE;

CREATE TABLE FWK_SERVICE (
	SERVICE_ID VARCHAR(30),
	SERVICE_NAME VARCHAR(100),
	SERVICE_DESC VARCHAR(300),
	CLASS_NAME VARCHAR(100),
	METHOD_NAME VARCHAR(50),
	SERVICE_TYPE VARCHAR(1),
	PRE_PROCESS_APP_ID VARCHAR(100),
	POST_PROCESS_APP_ID VARCHAR(100),
	TIME_CHECK_YN VARCHAR(1) DEFAULT 'N' ,
	START_TIME VARCHAR(4) DEFAULT '2400',
	END_TIME VARCHAR(4) DEFAULT '2400',
	BIZ_DAY_CHECK_YN VARCHAR(1) DEFAULT 'Y' ,
	USE_YN VARCHAR(1) DEFAULT 'Y' ,
	TRX_ID VARCHAR(40),
	ORG_ID VARCHAR(10),
	IO_TYPE VARCHAR(1),
	BIZ_GROUP_ID VARCHAR(20),
	WORK_SPACE_ID VARCHAR(20),
	LOGIN_ONLY_YN VARCHAR(1) DEFAULT 'Y' ,
	SECURE_SIGN_YN VARCHAR(1) DEFAULT 'N' ,
	REQ_CHANNEL_CODE VARCHAR(1) DEFAULT '3',
	SVC_CONF_1 VARCHAR(20),
	SVC_CONF_2 VARCHAR(20),
	BANK_STATUS_CHECK_YN VARCHAR(1) DEFAULT 'N' ,
	BANK_CODE_FIELD VARCHAR(30),
	BIZDAY_SERVICE_YN VARCHAR(1),
	BIZDAY_SERVICE_START_TIME VARCHAR(4),
	BIZDAY_SERVICE_END_TIME VARCHAR(4),
	SATURDAY_SERVICE_YN VARCHAR(1),
	SATURDAY_SERVICE_START_TIME VARCHAR(4),
	SATURDAY_SERVICE_END_TIME VARCHAR(4),
	HOLIDAY_SERVICE_YN VARCHAR(1),
	HOLIDAY_SERVICE_START_TIME VARCHAR(4),
	HOLIDAY_SERVICE_END_TIME VARCHAR(4),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL,
	LAST_UPDATE_USER_ID VARCHAR(20),
	CONSTRAINT PK_FWK_SERVICE PRIMARY KEY (SERVICE_ID),
	CONSTRAINT SYS_C0012426 CHECK (SERVICE_ID IS NOT NULL),
	CONSTRAINT SYS_C0012427 CHECK (SERVICE_NAME IS NOT NULL),
	CONSTRAINT SYS_C0012428 CHECK (TIME_CHECK_YN IS NOT NULL),
	CONSTRAINT SYS_C0012429 CHECK (BIZ_DAY_CHECK_YN IS NOT NULL),
	CONSTRAINT SYS_C0012430 CHECK (USE_YN IS NOT NULL),
	CONSTRAINT SYS_C0012431 CHECK (LOGIN_ONLY_YN IS NOT NULL),
	CONSTRAINT SYS_C0012432 CHECK (SECURE_SIGN_YN IS NOT NULL),
	CONSTRAINT SYS_C0012433 CHECK (BANK_STATUS_CHECK_YN IS NOT NULL)
);
