-- FWK_MESSAGE_FIELD_MAPPING definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_MESSAGE_FIELD_MAPPING;

CREATE TABLE FWK_MESSAGE_FIELD_MAPPING (
	TRG_ORG_ID VARCHAR(10),
	TRG_MESSAGE_ID VARCHAR(50),
	SRC_ORG_ID VARCHAR(10),
	TRG_MESSAGE_FIELD_ID VARCHAR(50),
	SRC_MESSAGE_ID VARCHAR(50),
	MAPPING_EXPR VARCHAR(500),
	SRC_PARENT_MESSAGE_FIELD_ID VARCHAR(50),
	TRG_PARENT_MESSAGE_FIELD_ID VARCHAR(50),
	CONSTRAINT SYS_C0014984 CHECK (TRG_ORG_ID IS NOT NULL),
	CONSTRAINT SYS_C0014985 CHECK (TRG_MESSAGE_ID IS NOT NULL),
	CONSTRAINT SYS_C0014986 CHECK (SRC_ORG_ID IS NOT NULL),
	CONSTRAINT SYS_C0014989 CHECK (TRG_MESSAGE_FIELD_ID IS NOT NULL),
	CONSTRAINT SYS_C0014990 CHECK (SRC_MESSAGE_ID IS NOT NULL)
);
