-- FWK_TRX_STOP_HISTORY definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_TRX_STOP_HISTORY;

CREATE TABLE FWK_TRX_STOP_HISTORY (
	GUBUN_TYPE VARCHAR(1),
	TRX_STOP_UPDATE_DTIME VARCHAR(14),
	TRX_ID VARCHAR(40),
	TRX_STOP_REASON VARCHAR(50),
	LAST_UPDATE_USER_ID VARCHAR(20),
	TRX_STOP_YN VARCHAR(1),
	CONSTRAINT PK_BIZ_STOP_HIS PRIMARY KEY (GUBUN_TYPE,TRX_STOP_UPDATE_DTIME,TRX_ID),
	CONSTRAINT SYS_C0012763 CHECK (GUBUN_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0012764 CHECK (TRX_STOP_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0012765 CHECK (TRX_ID IS NOT NULL),
	CONSTRAINT SYS_C0012766 CHECK (LAST_UPDATE_USER_ID IS NOT NULL)
);
