-- FWK_ORG_CODE definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_ORG_CODE;

CREATE TABLE FWK_ORG_CODE (
	ORG_ID VARCHAR(10),
	CODE_GROUP_ID VARCHAR(8),
	CODE VARCHAR(30),
	ORG_CODE VARCHAR(30),
	PRIORITY VARCHAR(3) DEFAULT '1',
	CONSTRAINT PK_FWK_ORG_CODE PRIMARY KEY (ORG_ID,CODE_GROUP_ID,CODE,ORG_CODE),
	CONSTRAINT SYS_C0012318 CHECK (ORG_ID IS NOT NULL),
	CONSTRAINT SYS_C0012319 CHECK (CODE_GROUP_ID IS NOT NULL),
	CONSTRAINT SYS_C0012320 CHECK (CODE IS NOT NULL),
	CONSTRAINT SYS_C0012321 CHECK (ORG_CODE IS NOT NULL)
);
