-- FWK_TRANS_DATA_HIS definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_TRANS_DATA_HIS;

CREATE TABLE FWK_TRANS_DATA_HIS (
	TRAN_SEQ VARCHAR(14),
	TRAN_ID VARCHAR(50),
	TRAN_TYPE VARCHAR(10),
	TRAN_NAME VARCHAR(100),
	TRAN_RESULT VARCHAR(1),
	TRAN_FAIL_REASON VARCHAR(2000),
	TRAN_FAIL_SQL VARCHAR(2000),
	TRAN_TIME VARCHAR(14),
	CONSTRAINT PK_FWK_TRANS_DATA_HIS PRIMARY KEY (TRAN_SEQ,TRAN_ID,TRAN_TYPE),
	CONSTRAINT SYS_C0012726 CHECK (TRAN_SEQ IS NOT NULL),
	CONSTRAINT SYS_C0012727 CHECK (TRAN_ID IS NOT NULL),
	CONSTRAINT SYS_C0012728 CHECK (TRAN_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0012729 CHECK (TRAN_RESULT IS NOT NULL),
	CONSTRAINT SYS_C0012730 CHECK (TRAN_TIME IS NOT NULL)
);
