-- FWK_ERROR_HANDLE_APP definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_ERROR_HANDLE_APP;

CREATE TABLE FWK_ERROR_HANDLE_APP (
	ERROR_CODE VARCHAR(40),
	HANDLE_APP_ID VARCHAR(50),
	USER_PARAM_VALUE VARCHAR(1000),
	CONSTRAINT PK_FWK_ERROR_HANDLE_APP PRIMARY KEY (ERROR_CODE,HANDLE_APP_ID),
	CONSTRAINT SYS_C0011311 CHECK (ERROR_CODE IS NOT NULL),
	CONSTRAINT SYS_C0011312 CHECK (HANDLE_APP_ID IS NOT NULL)
);
