-- FWK_WAS_PROPERTY definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_WAS_PROPERTY;

CREATE TABLE FWK_WAS_PROPERTY (
	INSTANCE_ID VARCHAR(4),
	PROPERTY_GROUP_ID VARCHAR(20),
	PROPERTY_ID VARCHAR(50),
	PROPERTY_VALUE VARCHAR(1000),
	PROPERTY_DESC VARCHAR(1000),
	CUR_VERSION BIGINT,
	FINAL_APPROVAL_STATE VARCHAR(1),
	FINAL_APPROVAL_DTIME VARCHAR(14),
	FINAL_APPROVAL_USER_ID VARCHAR(20),
	FINAL_APPROVAL_USER_NAME VARCHAR(50),
	CONSTRAINT PK_FWK_WAS_PROPERTY PRIMARY KEY (INSTANCE_ID,PROPERTY_GROUP_ID,PROPERTY_ID),
	CONSTRAINT SYS_C0012812 CHECK (INSTANCE_ID IS NOT NULL),
	CONSTRAINT SYS_C0012813 CHECK (PROPERTY_GROUP_ID IS NOT NULL),
	CONSTRAINT SYS_C0012814 CHECK (PROPERTY_ID IS NOT NULL),
	CONSTRAINT SYS_C0012815 CHECK (PROPERTY_VALUE IS NOT NULL)
);
