-- FWK_ROLE_MENU definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_ROLE_MENU;

CREATE TABLE FWK_ROLE_MENU (
	ROLE_ID VARCHAR(10),
	MENU_ID VARCHAR(40),
	AUTH_CODE VARCHAR(1),
	FINAL_APPROVAL_STATE VARCHAR(1),
	FINAL_APPROVAL_DTIME VARCHAR(14),
	FINAL_APPROVAL_USER_ID VARCHAR(20),
	FINAL_APPROVAL_USER_NAME VARCHAR(50),
	CONSTRAINT PK_FWK_ROLE_MENU PRIMARY KEY (ROLE_ID,MENU_ID),
	CONSTRAINT SYS_C0012397 CHECK (ROLE_ID IS NOT NULL),
	CONSTRAINT SYS_C0012398 CHECK (MENU_ID IS NOT NULL),
	CONSTRAINT SYS_C0012399 CHECK (AUTH_CODE IS NOT NULL)
);
