-- FWK_COMPONENT definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_COMPONENT;

CREATE TABLE FWK_COMPONENT (
	COMPONENT_ID VARCHAR(50),
	COMPONENT_NAME VARCHAR(100),
	COMPONENT_DESC VARCHAR(300),
	COMPONENT_TYPE VARCHAR(1),
	COMPONENT_CLASS_NAME VARCHAR(100),
	COMPONENT_METHOD_NAME VARCHAR(50),
	COMPONENT_CREATE_TYPE VARCHAR(1),
	BIZ_GROUP_ID VARCHAR(20),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL,
	LAST_UPDATE_USER_ID VARCHAR(20),
	USE_YN VARCHAR(1) DEFAULT 'Y'
   ,
	CONSTRAINT PK_FWK_COMPONENT PRIMARY KEY (COMPONENT_ID),
	CONSTRAINT SYS_C0011226 CHECK (COMPONENT_ID IS NOT NULL),
	CONSTRAINT SYS_C0011227 CHECK (COMPONENT_NAME IS NOT NULL),
	CONSTRAINT SYS_C0011228 CHECK (COMPONENT_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0011229 CHECK (COMPONENT_CLASS_NAME IS NOT NULL),
	CONSTRAINT SYS_C0011230 CHECK (COMPONENT_METHOD_NAME IS NOT NULL)
);
