-- FWK_WAS_GROUP definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_WAS_GROUP;

CREATE TABLE FWK_WAS_GROUP (
	WAS_GROUP_ID VARCHAR(20),
	WAS_GROUP_NAME VARCHAR(50),
	WAS_GROUP_DESC VARCHAR(200),
	CONSTRAINT PK_WAS_GROUP PRIMARY KEY (WAS_GROUP_ID),
	CONSTRAINT SYS_C0012801 CHECK (WAS_GROUP_ID IS NOT NULL)
);
