-- FWK_MESSAGE_TEST definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_MESSAGE_TEST;

CREATE TABLE FWK_MESSAGE_TEST (
	TEST_SNO DECIMAL(30,0),
	USER_ID VARCHAR(20),
	ORG_ID VARCHAR(10),
	MESSAGE_ID VARCHAR(30),
	HEADER_YN VARCHAR(1),
	XML_YN VARCHAR(1),
	TEST_NAME VARCHAR(50),
	TEST_DESC VARCHAR(500),
	TEST_DATA VARCHAR(4000),
	TEST_DATA1 VARCHAR(4000),
	TEST_DATA2 VARCHAR(4000),
	TEST_DATA3 VARCHAR(4000),
	TEST_DATA4 VARCHAR(4000),
	TEST_GROUP_ID VARCHAR(20),
	TRX_ID VARCHAR(50),
	DEFAULT_PROXY_YN VARCHAR(1),
	TEST_HEADER_DATA TEXT,
	TEST_HEADER_USE_YN VARCHAR(1),
	PROXY_FIELD VARCHAR(50),
	PROXY_VALUE VARCHAR(100),
	LAST_UPDATE_DTIME VARCHAR(14),
	LAST_UPDATE_USERID VARCHAR(20),
	TEST_HEADER_DATA1 VARCHAR(4000),
	CONSTRAINT FWK_MESSAGE_TEST_PK PRIMARY KEY (TEST_SNO),
	CONSTRAINT SYS_C0015376 CHECK (TEST_SNO IS NOT NULL),
	CONSTRAINT SYS_C0015377 CHECK (USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0015379 CHECK (ORG_ID IS NOT NULL),
	CONSTRAINT SYS_C0015380 CHECK (MESSAGE_ID IS NOT NULL),
	CONSTRAINT SYS_C0015381 CHECK (HEADER_YN IS NOT NULL),
	CONSTRAINT SYS_C0015383 CHECK (XML_YN IS NOT NULL),
	CONSTRAINT SYS_C0015385 CHECK (TEST_NAME IS NOT NULL)
);
