-- FWK_WAS_EXEC_BATCH definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_WAS_EXEC_BATCH;

CREATE TABLE FWK_WAS_EXEC_BATCH (
	BATCH_APP_ID VARCHAR(50),
	INSTANCE_ID VARCHAR(4),
	USE_YN VARCHAR(1) DEFAULT 'Y',
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	CONSTRAINT PK_WAS_EXEC_BATCH PRIMARY KEY (BATCH_APP_ID,INSTANCE_ID),
	CONSTRAINT SYS_C0012796 CHECK (BATCH_APP_ID IS NOT NULL),
	CONSTRAINT SYS_C0012797 CHECK (INSTANCE_ID IS NOT NULL),
	CONSTRAINT SYS_C0012798 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0012799 CHECK (LAST_UPDATE_USER_ID IS NOT NULL)
);
