-- FWK_CODE_GROUP definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_CODE_GROUP;

CREATE TABLE FWK_CODE_GROUP (
	CODE_GROUP_ID VARCHAR(8),
	CODE_GROUP_NAME VARCHAR(100),
	CODE_GROUP_DESC VARCHAR(200),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL,
	LAST_UPDATE_USER_ID VARCHAR(20),
	BIZ_GROUP_ID VARCHAR(20),
	FINAL_APPROVAL_STATE VARCHAR(1),
	FINAL_APPROVAL_DTIME VARCHAR(14),
	FINAL_APPROVAL_USER_ID VARCHAR(20),
	FINAL_APPROVAL_USER_NAME VARCHAR(50),
	CONSTRAINT PK_FWK_CODE_GROUP PRIMARY KEY (CODE_GROUP_ID),
	CONSTRAINT SYS_C0011208 CHECK (CODE_GROUP_ID IS NOT NULL),
	CONSTRAINT SYS_C0011209 CHECK (CODE_GROUP_NAME IS NOT NULL)
);
