-- FWK_LISTENER_CONNECTOR_MAPPING definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_LISTENER_CONNECTOR_MAPPING;

CREATE TABLE FWK_LISTENER_CONNECTOR_MAPPING (
	LISTENER_GW_ID VARCHAR(20),
	LISTENER_SYSTEM_ID VARCHAR(20),
	IDENTIFIER VARCHAR(100),
	CONNECTOR_GW_ID VARCHAR(20),
	CONNECTOR_SYSTEM_ID VARCHAR(20),
	DESCRIPTION VARCHAR(200),
	CONSTRAINT FWK_LISTENER_CONNECTOR_MAPP_PK PRIMARY KEY (LISTENER_GW_ID,LISTENER_SYSTEM_ID,IDENTIFIER),
	CONSTRAINT SYS_C0012246 CHECK (LISTENER_GW_ID IS NOT NULL),
	CONSTRAINT SYS_C0012247 CHECK (LISTENER_SYSTEM_ID IS NOT NULL),
	CONSTRAINT SYS_C0012248 CHECK (IDENTIFIER IS NOT NULL),
	CONSTRAINT SYS_C0012249 CHECK (CONNECTOR_GW_ID IS NOT NULL),
	CONSTRAINT SYS_C0012250 CHECK (CONNECTOR_SYSTEM_ID IS NOT NULL)
);
