-- FWK_RELATION_PARAM definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_RELATION_PARAM;

CREATE TABLE FWK_RELATION_PARAM (
	SERVICE_ID VARCHAR(30),
	SERVICE_SEQ_NO DECIMAL(3,0) DEFAULT 0 ,
	COMPONENT_ID VARCHAR(40),
	PARAM_SEQ_NO DECIMAL(8,0),
	PARAM_VALUE VARCHAR(500),
	LAST_UPDATE_DTIME VARCHAR(14),
	CONSTRAINT PK_FWK_RELATION_PARAM PRIMARY KEY (SERVICE_ID,SERVICE_SEQ_NO,COMPONENT_ID,PARAM_SEQ_NO),
	CONSTRAINT SYS_C0012381 CHECK (SERVICE_ID IS NOT NULL),
	CONSTRAINT SYS_C0012382 CHECK (SERVICE_SEQ_NO IS NOT NULL),
	CONSTRAINT SYS_C0012383 CHECK (COMPONENT_ID IS NOT NULL),
	CONSTRAINT SYS_C0012384 CHECK (PARAM_SEQ_NO IS NOT NULL)
);
