-- Security DDL for H2 (local development)

CREATE TABLE IF NOT EXISTS FWK_USER (
    USER_ID VARCHAR(20) NOT NULL,
    USER_NAME VARCHAR(50),
    PASSWORD VARCHAR(50),
    ROLE_ID VARCHAR(10),
    POSITION_NAME VARCHAR(100),
    ADDRESS VARCHAR(200),
    CLASS_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    USER_STATE_CODE VARCHAR(1),
    LAST_UPDATE_DTIME VARCHAR(14),
    LAST_UPDATE_USER_ID VARCHAR(20),
    ACCESS_IP VARCHAR(15) DEFAULT '*',
    USER_SSN VARCHAR(13),
    PHONE VARCHAR(13),
    REG_REQ_USER_NAME VARCHAR(10),
    TITLE_NAME VARCHAR(10),
    EMP_NO VARCHAR(10),
    BRANCH_NO VARCHAR(10),
    BIZ_AUTH_CODE VARCHAR(100),
    LOGIN_FAIL_COUNT DECIMAL(1,0) DEFAULT 0,
    LAST_PWD_UPDATE_DTIME VARCHAR(14),
    DEFAULT_PROJECT_ID VARCHAR(20),
    PASSWD VARCHAR(100),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS FWK_ROLE (
    ROLE_ID VARCHAR(10) NOT NULL,
    ROLE_NAME VARCHAR(50),
    USE_YN VARCHAR(1) DEFAULT 'Y',
    ROLE_DESC VARCHAR(200),
    LAST_UPDATE_DTIME VARCHAR(14),
    LAST_UPDATE_USER_ID VARCHAR(20),
    PRIMARY KEY (ROLE_ID)
);

CREATE TABLE IF NOT EXISTS FWK_MENU (
    MENU_ID VARCHAR(40) NOT NULL,
    PRIOR_MENU_ID VARCHAR(40),
    SORT_ORDER DECIMAL(3,0) DEFAULT 0,
    MENU_NAME VARCHAR(100),
    MENU_URL VARCHAR(200),
    MENU_IMAGE VARCHAR(50),
    DISPLAY_YN VARCHAR(1) DEFAULT 'Y',
    USE_YN VARCHAR(1) DEFAULT 'Y',
    LAST_UPDATE_DTIME VARCHAR(14),
    LAST_UPDATE_USER_ID VARCHAR(20),
    PRIMARY KEY (MENU_ID)
);

CREATE TABLE IF NOT EXISTS FWK_USER_MENU (
    USER_ID VARCHAR(20) NOT NULL,
    MENU_ID VARCHAR(40) NOT NULL,
    AUTH_CODE VARCHAR(1) NOT NULL,
    LAST_UPDATE_DTIME VARCHAR(14),
    LAST_UPDATE_USER_ID VARCHAR(20),
    FAVOR_MENU_ORDER DECIMAL(3,0) DEFAULT 0,
    PRIMARY KEY (USER_ID, MENU_ID)
);

CREATE TABLE IF NOT EXISTS FWK_ROLE_MENU (
    ROLE_ID VARCHAR(10) NOT NULL,
    MENU_ID VARCHAR(40) NOT NULL,
    AUTH_CODE VARCHAR(1) NOT NULL,
    PRIMARY KEY (ROLE_ID, MENU_ID)
);

CREATE TABLE IF NOT EXISTS FWK_USER_ACCESS_HIS (
    USER_ID VARCHAR(20) NOT NULL,
    ACCESS_DTIME VARCHAR(14) NOT NULL,
    ACCESS_IP VARCHAR(200),
    ACCESS_URL VARCHAR(1000),
    INPUT_DATA VARCHAR(4000),
    RESULT_MESSAGE VARCHAR(200)
);
