-- FWK_ARTICLE_USER definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_ARTICLE_USER;

CREATE TABLE FWK_ARTICLE_USER (
	USER_ID VARCHAR(20),
	BOARD_ID VARCHAR(20),
	ARTICLE_SEQ BIGINT,
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	CONSTRAINT SYS_C0011078 CHECK (USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0011079 CHECK (BOARD_ID IS NOT NULL),
	CONSTRAINT SYS_C0011080 CHECK (ARTICLE_SEQ IS NOT NULL),
	CONSTRAINT SYS_C0011081 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0011082 PRIMARY KEY (USER_ID,BOARD_ID,ARTICLE_SEQ)
);
