-- FWK_TRX definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_TRX;

CREATE TABLE FWK_TRX (
	TRX_ID VARCHAR(40),
	OPER_MODE_TYPE VARCHAR(1),
	TRX_STOP_YN VARCHAR(1) DEFAULT 'Y',
	TRX_NAME VARCHAR(50),
	TRX_DESC VARCHAR(200),
	TRX_TYPE VARCHAR(1) DEFAULT '1' ,
	RETRY_TRX_YN VARCHAR(1) DEFAULT 'N' ,
	MAX_RETRY_COUNT DECIMAL(3,0) DEFAULT 0 ,
	RETRY_MI_CYCLE VARCHAR(4),
	BIZ_GROUP_ID VARCHAR(10),
	BIZDAY_TRX_YN VARCHAR(1),
	BIZDAY_TRX_START_TIME VARCHAR(4),
	BIZDAY_TRX_END_TIME VARCHAR(4),
	SATURDAY_TRX_YN VARCHAR(1),
	SATURDAY_TRX_START_TIME VARCHAR(4),
	SATURDAY_TRX_END_TIME VARCHAR(4),
	HOLIDAY_TRX_YN VARCHAR(1),
	HOLIDAY_TRX_START_TIME VARCHAR(4),
	HOLIDAY_TRX_END_TIME VARCHAR(4),
	TRX_STOP_REASON VARCHAR(200),
	CONSTRAINT PK_FWK_TRX PRIMARY KEY (TRX_ID),
	CONSTRAINT SYS_C0012737 CHECK (TRX_ID IS NOT NULL),
	CONSTRAINT SYS_C0012738 CHECK (TRX_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0012739 CHECK (RETRY_TRX_YN IS NOT NULL),
	CONSTRAINT SYS_C0012740 CHECK (MAX_RETRY_COUNT IS NOT NULL)
);
