-- FWK_TRX_HISTORY definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_TRX_HISTORY;

CREATE TABLE FWK_TRX_HISTORY (
	TRX_ID VARCHAR(40),
	OPER_MODE_TYPE VARCHAR(1),
	TRX_STOP_YN VARCHAR(1) DEFAULT 'Y',
	TRX_NAME VARCHAR(50),
	TRX_DESC VARCHAR(200),
	TRX_TYPE VARCHAR(1) DEFAULT '1' ,
	RETRY_TRX_YN VARCHAR(1) DEFAULT 'N' ,
	MAX_RETRY_COUNT DECIMAL(3,0) DEFAULT 0 ,
	RETRY_MI_CYCLE VARCHAR(4),
	BIZ_GROUP_ID VARCHAR(10),
	BIZDAY_TRX_YN VARCHAR(1),
	BIZDAY_TRX_START_TIME VARCHAR(4),
	BIZDAY_TRX_END_TIME VARCHAR(4),
	SATURDAY_TRX_YN VARCHAR(1),
	SATURDAY_TRX_START_TIME VARCHAR(4),
	SATURDAY_TRX_END_TIME VARCHAR(4),
	HOLIDAY_TRX_YN VARCHAR(1),
	HOLIDAY_TRX_START_TIME VARCHAR(4),
	HOLIDAY_TRX_END_TIME VARCHAR(4),
	TRX_STOP_REASON VARCHAR(200),
	VERSION DECIMAL(3,0),
	HISTORY_REASON VARCHAR(100),
	CONSTRAINT PK_FWK_TRX_HISTORY PRIMARY KEY (TRX_ID,VERSION),
	CONSTRAINT SYS_C0012742 CHECK (TRX_ID IS NOT NULL),
	CONSTRAINT SYS_C0012743 CHECK (TRX_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0012744 CHECK (RETRY_TRX_YN IS NOT NULL),
	CONSTRAINT SYS_C0012745 CHECK (MAX_RETRY_COUNT IS NOT NULL),
	CONSTRAINT SYS_C0012746 CHECK (VERSION IS NOT NULL)
);
