-- FWK_WAS_GROUP_INSTANCE definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_WAS_GROUP_INSTANCE;

CREATE TABLE FWK_WAS_GROUP_INSTANCE (
	WAS_GROUP_ID VARCHAR(20),
	INSTANCE_ID VARCHAR(4),
	CONSTRAINT PK_GROUP_INSTANCE PRIMARY KEY (WAS_GROUP_ID,INSTANCE_ID),
	CONSTRAINT SYS_C0012803 CHECK (WAS_GROUP_ID IS NOT NULL),
	CONSTRAINT SYS_C0012804 CHECK (INSTANCE_ID IS NOT NULL)
);
