-- FWK_SERVICE_RELATION definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_SERVICE_RELATION;

CREATE TABLE FWK_SERVICE_RELATION (
	SERVICE_ID VARCHAR(30),
	SERVICE_SEQ_NO DECIMAL(3,0) DEFAULT 1 ,
	COMPONENT_ID VARCHAR(40),
	POST_CONDITION VARCHAR(30),
	EXPRESSION VARCHAR(100),
	RELATION_ETC1 VARCHAR(500),
	RELATION_ETC2 VARCHAR(500),
	RELATION_ETC3 VARCHAR(500),
	RELATION_ETC4 VARCHAR(500),
	LAST_UPDATE_DTIME VARCHAR(14),
	CONSTRAINT PK_FWK_SERVICE_RELATION PRIMARY KEY (SERVICE_ID,SERVICE_SEQ_NO),
	CONSTRAINT SYS_C0012457 CHECK (SERVICE_ID IS NOT NULL),
	CONSTRAINT SYS_C0012458 CHECK (SERVICE_SEQ_NO IS NOT NULL),
	CONSTRAINT SYS_C0012459 CHECK (COMPONENT_ID IS NOT NULL)
);
