-- FWK_MESSAGE_INSTANCE definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_MESSAGE_INSTANCE;

CREATE TABLE FWK_MESSAGE_INSTANCE (
	MESSAGE_SNO VARCHAR(30),
	TRX_ID VARCHAR(40),
	ORG_ID VARCHAR(10),
	IO_TYPE VARCHAR(1),
	REQ_RES_TYPE VARCHAR(1),
	MESSAGE_ID VARCHAR(50),
	TRX_TRACKING_NO VARCHAR(30),
	USER_ID VARCHAR(20),
	LOG_DTIME VARCHAR(17),
	LAST_LOG_DTIME VARCHAR(17),
	LAST_RT_CODE VARCHAR(40),
	INSTANCE_ID VARCHAR(4),
	RETRY_TRX_YN VARCHAR(1),
	MESSAGE_DATA VARCHAR(4000),
	TRX_DTIME VARCHAR(14) DEFAULT NULL ,
	CHANNEL_TYPE VARCHAR(10),
	URI VARCHAR(200),
	LOG_DATA TEXT,
	LOG_DATA2 VARCHAR(4000),
	LOG_DATA3 VARCHAR(4000),
	LOG_DATA4 VARCHAR(4000),
	TESTCASE_ID VARCHAR(50),
	TESTCASE_SNO DECIMAL(30,0),
	SUCCESS_YN VARCHAR(1),
	CONSTRAINT SYS_C0015277 CHECK (MESSAGE_SNO IS NOT NULL),
	CONSTRAINT SYS_C0015278 CHECK (TRX_ID IS NOT NULL),
	CONSTRAINT SYS_C0015285 CHECK (ORG_ID IS NOT NULL),
	CONSTRAINT SYS_C0015286 CHECK (IO_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0015287 CHECK (REQ_RES_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0015288 CHECK (MESSAGE_ID IS NOT NULL),
	CONSTRAINT SYS_C0015289 CHECK (TRX_TRACKING_NO IS NOT NULL),
	CONSTRAINT SYS_C0015290 CHECK (USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0015291 CHECK (LOG_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0015292 CHECK (LAST_LOG_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0015293 CHECK (LAST_RT_CODE IS NOT NULL),
	CONSTRAINT SYS_C0015299 CHECK (INSTANCE_ID IS NOT NULL),
	CONSTRAINT SYS_C0015300 CHECK (RETRY_TRX_YN IS NOT NULL),
	CONSTRAINT SYS_C0015302 CHECK (TRX_DTIME IS NOT NULL)
);