-- FWK_BIZ_GROUP definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_BIZ_GROUP;

CREATE TABLE FWK_BIZ_GROUP (
	BIZ_GROUP_ID VARCHAR(20),
	BIZ_GROUP_NAME VARCHAR(50),
	BIZ_GROUP_DESC VARCHAR(200),
	BIZ_L_GROUP_ID VARCHAR(20),
	BIZ_L_GROUP_NAME VARCHAR(50),
	BIZ_SUB_GROUP_ID VARCHAR(20),
	BIZ_SUB_GROUP_NAME VARCHAR(50),
	DEFAULT_WORK_SPACE_ID VARCHAR(20),
	"DEPTH" VARCHAR(1),
	BIZ_DOMAIN VARCHAR(10),
	KOR_PATH_TEXT VARCHAR(100),
	ENG_PKG_TEXT VARCHAR(50),
	CONSTRAINT PK_BIZ_GROUP PRIMARY KEY (BIZ_GROUP_ID),
	CONSTRAINT SYS_C0011113 CHECK (BIZ_GROUP_ID IS NOT NULL),
	CONSTRAINT SYS_C0011114 CHECK (BIZ_L_GROUP_ID IS NOT NULL)
);
