-- FWK_HANDLE_APP definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_HANDLE_APP;

CREATE TABLE FWK_HANDLE_APP (
	HANDLE_APP_ID VARCHAR(50),
	HANDLE_APP_NAME VARCHAR(50),
	HANDLE_APP_DESC VARCHAR(200),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	SYS_PARAM_VALUE VARCHAR(1000),
	PARAM_DESC VARCHAR(2000),
	HANDLE_APP_FILE VARCHAR(100),
	CONSTRAINT PK_FWK_HANDLE_APP PRIMARY KEY (HANDLE_APP_ID),
	CONSTRAINT SYS_C0011579 CHECK (HANDLE_APP_ID IS NOT NULL),
	CONSTRAINT SYS_C0011580 CHECK (HANDLE_APP_NAME IS NOT NULL),
	CONSTRAINT SYS_C0011581 CHECK (HANDLE_APP_DESC IS NOT NULL),
	CONSTRAINT SYS_C0011582 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0011583 CHECK (LAST_UPDATE_USER_ID IS NOT NULL)
);
