-- FWK_MESSAGE_HANDLER definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_MESSAGE_HANDLER;

CREATE TABLE FWK_MESSAGE_HANDLER (
	ORG_ID VARCHAR(10),
	TRX_TYPE VARCHAR(1),
	IO_TYPE VARCHAR(1),
	HANDLER VARCHAR(200),
	HANDLER_DESC VARCHAR(2000),
	STOP_YN VARCHAR(1) DEFAULT 'N' ,
	LAST_UPDATE_DTIME VARCHAR(14),
	LAST_UPDATE_USER_ID VARCHAR(20),
	OPER_MODE_TYPE VARCHAR(1),
	CONSTRAINT FWK_MESSAGE_HANDLER_PK PRIMARY KEY (ORG_ID,TRX_TYPE,IO_TYPE,OPER_MODE_TYPE),
	CONSTRAINT SYS_C0015053 CHECK (ORG_ID IS NOT NULL),
	CONSTRAINT SYS_C0015054 CHECK (TRX_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0015055 CHECK (IO_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0015061 CHECK (STOP_YN IS NOT NULL),
	CONSTRAINT SYS_C0015063 CHECK (OPER_MODE_TYPE IS NOT NULL)
);
