-- FWK_USER_ACCESS_HIS definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_USER_ACCESS_HIS;

CREATE TABLE FWK_USER_ACCESS_HIS (
	USER_ID VARCHAR(20),
	ACCESS_DTIME VARCHAR(14) DEFAULT NULL ,
	ACCESS_IP VARCHAR(200),
	ACCESS_URL VARCHAR(1000),
	INPUT_DATA VARCHAR(4000),
	RESULT_MESSAGE VARCHAR(200),
	CONSTRAINT SYS_C0012775 CHECK (USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0012776 CHECK (ACCESS_DTIME IS NOT NULL)
);
CREATE INDEX ACCESS_HIS_DTIME_IDX ON FWK_USER_ACCESS_HIS (ACCESS_DTIME,USER_ID);
CREATE INDEX ACCESS_HIS_USER_ID_IDX ON FWK_USER_ACCESS_HIS (USER_ID,ACCESS_DTIME);