-- FWK_VALIDATOR definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_VALIDATOR;

CREATE TABLE FWK_VALIDATOR (
	VALIDATOR_ID VARCHAR(20),
	VALIDATOR_NAME VARCHAR(50),
	VALIDATOR_DESC VARCHAR(200),
	BIZ_DOMAIN VARCHAR(10),
	JAVA_CLASS_NAME VARCHAR(100),
	USE_YN VARCHAR(1) DEFAULT 'Y' ,
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	CONSTRAINT PK_FWK_VALIDATOR PRIMARY KEY (VALIDATOR_ID),
	CONSTRAINT SYS_C0012788 CHECK (VALIDATOR_ID IS NOT NULL),
	CONSTRAINT SYS_C0012789 CHECK (VALIDATOR_NAME IS NOT NULL),
	CONSTRAINT SYS_C0012790 CHECK (BIZ_DOMAIN IS NOT NULL),
	CONSTRAINT SYS_C0012791 CHECK (JAVA_CLASS_NAME IS NOT NULL),
	CONSTRAINT SYS_C0012792 CHECK (USE_YN IS NOT NULL),
	CONSTRAINT SYS_C0012793 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0012794 CHECK (LAST_UPDATE_USER_ID IS NOT NULL)
);
