-- FWK_ACCESS_USER definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_ACCESS_USER;

CREATE TABLE FWK_ACCESS_USER (
	TRX_ID VARCHAR(50),
	CUST_USER_ID VARCHAR(50),
	USE_YN VARCHAR(1) DEFAULT 'Y',
	GUBUN_TYPE VARCHAR(1),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	CONSTRAINT PK_FWK_ACCESS_USER PRIMARY KEY (GUBUN_TYPE,TRX_ID,CUST_USER_ID),
	CONSTRAINT SYS_C0011609 CHECK (TRX_ID IS NOT NULL),
	CONSTRAINT SYS_C0011610 CHECK (CUST_USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0011611 CHECK (GUBUN_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0011612 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0011613 CHECK (LAST_UPDATE_USER_ID IS NOT NULL)
);
