-- FWK_ERROR definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_ERROR;

CREATE TABLE FWK_ERROR (
	ERROR_CODE VARCHAR(40),
	TRX_ID VARCHAR(40),
	ERROR_TITLE VARCHAR(200),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	ORG_ID VARCHAR(10),
	ORG_ERROR_CODE VARCHAR(20),
	ERROR_LEVEL VARCHAR(1) DEFAULT '1' ,
	ERROR_HTTPCODE VARCHAR(20),
	FINAL_APPROVAL_STATE VARCHAR(1),
	FINAL_APPROVAL_DTIME VARCHAR(14),
	FINAL_APPROVAL_USER_ID VARCHAR(20),
	FINAL_APPROVAL_USER_NAME VARCHAR(50),
	CONSTRAINT PK_FWK_ERROR PRIMARY KEY (ERROR_CODE),
	CONSTRAINT SYS_C0011615 CHECK (ERROR_CODE IS NOT NULL),
	CONSTRAINT SYS_C0011616 CHECK (ERROR_TITLE IS NOT NULL),
	CONSTRAINT SYS_C0011617 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0011618 CHECK (LAST_UPDATE_USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0011619 CHECK (ERROR_LEVEL IS NOT NULL)
);
