-- FWK_WAS_PROPERTY_HISTORY definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_WAS_PROPERTY_HISTORY;

CREATE TABLE FWK_WAS_PROPERTY_HISTORY (
	INSTANCE_ID VARCHAR(4),
	PROPERTY_GROUP_ID VARCHAR(20),
	PROPERTY_ID VARCHAR(50),
	VERSION DECIMAL(5,0),
	PROPERTY_VALUE VARCHAR(1000),
	PROPERTY_DESC VARCHAR(1000),
	REASON VARCHAR(2000),
	LAST_UPDATE_USER_ID VARCHAR(20),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	CONSTRAINT PK_FWK_WAS_PROPERTY_HISTORY PRIMARY KEY (INSTANCE_ID,PROPERTY_GROUP_ID,PROPERTY_ID,VERSION),
	CONSTRAINT SYS_C0012817 CHECK (INSTANCE_ID IS NOT NULL),
	CONSTRAINT SYS_C0012818 CHECK (PROPERTY_GROUP_ID IS NOT NULL),
	CONSTRAINT SYS_C0012819 CHECK (PROPERTY_ID IS NOT NULL),
	CONSTRAINT SYS_C0012820 CHECK (VERSION IS NOT NULL),
	CONSTRAINT SYS_C0012821 CHECK (PROPERTY_VALUE IS NOT NULL),
	CONSTRAINT SYS_C0012822 CHECK (LAST_UPDATE_USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0012823 CHECK (LAST_UPDATE_DTIME IS NOT NULL)
);
