-- FWK_GATEWAY definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_GATEWAY;

CREATE TABLE FWK_GATEWAY (
	GW_ID VARCHAR(20),
	GW_NAME VARCHAR(200),
	THREAD_COUNT DECIMAL(3,0),
	GW_PROPERTIES VARCHAR(500),
	GW_DESC VARCHAR(1000),
	GW_APP_NAME VARCHAR(200) DEFAULT NULL,
	IO_TYPE VARCHAR(1) DEFAULT 'O' ,
	CONSTRAINT PK_FWK_GATEWAY PRIMARY KEY (GW_ID),
	CONSTRAINT SYS_C0011606 CHECK (GW_ID IS NOT NULL),
	CONSTRAINT SYS_C0011607 CHECK (IO_TYPE IS NOT NULL)
);
