-- FWK_ERROR_HIS definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_ERROR_HIS;

CREATE TABLE FWK_ERROR_HIS (
	ERROR_CODE VARCHAR(40),
	ERROR_SER_NO VARCHAR(28),
	CUST_USER_ID VARCHAR(20),
	ERROR_MESSAGE VARCHAR(500),
	ERROR_OCCUR_DTIME VARCHAR(14) DEFAULT NULL ,
	ERROR_URL VARCHAR(300),
	ERROR_TRACE VARCHAR(4000),
	ERROR_INSTANCE_ID VARCHAR(10),
	CONSTRAINT FWK_ERROR_HIS_PK PRIMARY KEY (ERROR_CODE,ERROR_SER_NO),
	CONSTRAINT SYS_C0014083 CHECK (ERROR_CODE IS NOT NULL),
	CONSTRAINT SYS_C0014084 CHECK (ERROR_SER_NO IS NOT NULL),
	CONSTRAINT SYS_C0014085 CHECK (CUST_USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0014086 CHECK (ERROR_OCCUR_DTIME IS NOT NULL)
);
