-- FWK_MESSAGE definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_MESSAGE;

CREATE TABLE FWK_MESSAGE (
	ORG_ID VARCHAR(10),
	MESSAGE_ID VARCHAR(50),
	MESSAGE_NAME VARCHAR(100),
	MESSAGE_DESC VARCHAR(200),
	MESSAGE_TYPE VARCHAR(1),
	PARENT_MESSAGE_ID VARCHAR(50),
	HEADER_YN VARCHAR(1) DEFAULT 'N',
	REQUEST_YN VARCHAR(2) DEFAULT NULL,
	TRX_TYPE VARCHAR(1) DEFAULT '1' ,
	PRE_LOAD_YN VARCHAR(1) DEFAULT 'N' ,
	LOG_LEVEL VARCHAR(1),
	BIZ_DOMAIN VARCHAR(10),
	VALIDATION_USE_YN VARCHAR(1) DEFAULT 'N' ,
	LOCK_YN VARCHAR(1) DEFAULT 'N' ,
	CUR_VERSION DECIMAL(3,0),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	CONSTRAINT PK_FWK_MESSAGE PRIMARY KEY (ORG_ID,MESSAGE_ID),
	CONSTRAINT SYS_C0014243 CHECK (ORG_ID IS NOT NULL),
	CONSTRAINT SYS_C0014244 CHECK (MESSAGE_ID IS NOT NULL),
	CONSTRAINT SYS_C0014245 CHECK (MESSAGE_NAME IS NOT NULL),
	CONSTRAINT SYS_C0014247 CHECK (TRX_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0014248 CHECK (PRE_LOAD_YN IS NOT NULL),
	CONSTRAINT SYS_C0014249 CHECK (VALIDATION_USE_YN IS NOT NULL),
	CONSTRAINT SYS_C0014250 CHECK (LOCK_YN IS NOT NULL),
	CONSTRAINT SYS_C0014251 CHECK (LAST_UPDATE_DTIME IS NOT NULL)
);
