-- FWK_MESSAGE_FIELD definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_MESSAGE_FIELD;

CREATE TABLE FWK_MESSAGE_FIELD (
	ORG_ID VARCHAR(10),
	MESSAGE_ID VARCHAR(50),
	MESSAGE_FIELD_ID VARCHAR(50),
	SORT_ORDER DECIMAL(4,0) DEFAULT 0 ,
	DATA_TYPE VARCHAR(1),
	DATA_LENGTH BIGINT,
	`SCALE` DECIMAL(2,0),
	ALIGN VARCHAR(1),
	FILLER VARCHAR(20),
	FIELD_TYPE VARCHAR(10),
	USE_MODE VARCHAR(20),
	REQUIRED_YN VARCHAR(1) DEFAULT 'Y',
	FIELD_TAG VARCHAR(500),
	CODE_GROUP VARCHAR(8),
	DEFAULT_VALUE VARCHAR(500),
	TEST_VALUE VARCHAR(500),
	REMARK VARCHAR(1) DEFAULT NULL,
	LOG_YN VARCHAR(1) DEFAULT 'Y',
	CODE_MAPPING_YN VARCHAR(1) DEFAULT 'N',
	MESSAGE_FIELD_NAME VARCHAR(100),
	MESSAGE_FIELD_DESC VARCHAR(200),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	VALIDATION_RULE_ID VARCHAR(20),
	LAST_UPDATE_USER_ID VARCHAR(20),
	FIELD_FORMAT VARCHAR(200),
	FIELD_FORMAT_DESC VARCHAR(500),
	FIELD_OPTION VARCHAR(200),
	FIELD_REPEAT_CNT DECIMAL(10,0),
	CONSTRAINT SYS_C0012975 CHECK (DATA_LENGTH IS NOT NULL),
	CONSTRAINT SYS_C0014481 CHECK (ORG_ID IS NOT NULL),
	CONSTRAINT SYS_C0014482 CHECK (MESSAGE_ID IS NOT NULL),
	CONSTRAINT SYS_C0014488 CHECK (MESSAGE_FIELD_ID IS NOT NULL),
	CONSTRAINT SYS_C0014490 CHECK (SORT_ORDER IS NOT NULL),
	CONSTRAINT SYS_C0014491 CHECK (DATA_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0014492 CHECK (ALIGN IS NOT NULL),
	CONSTRAINT SYS_C0014493 CHECK (LAST_UPDATE_DTIME IS NOT NULL)
);