-- FWK_SYSTEM definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_SYSTEM;

CREATE TABLE FWK_SYSTEM (
	GW_ID VARCHAR(20),
	SYSTEM_ID VARCHAR(20),
	OPER_MODE_TYPE VARCHAR(1),
	IP VARCHAR(15),
	PORT VARCHAR(5),
	STOP_YN VARCHAR(1) DEFAULT 'N',
	SYSTEM_DESC VARCHAR(1000),
	APPLIED_WAS_INSTANCE VARCHAR(100),
	CONSTRAINT PK_FWK_SYSTEM PRIMARY KEY (GW_ID,SYSTEM_ID),
	CONSTRAINT SYS_C0012492 CHECK (GW_ID IS NOT NULL),
	CONSTRAINT SYS_C0012493 CHECK (SYSTEM_ID IS NOT NULL)
);
