-- FWK_USER definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_USER;

CREATE TABLE FWK_USER (
	USER_ID VARCHAR(20),
	USER_NAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	ROLE_ID VARCHAR(10),
	POSITION_NAME VARCHAR(100),
	ADDRESS VARCHAR(200),
	CLASS_NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	USER_STATE_CODE VARCHAR(1),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	ACCESS_IP VARCHAR(15) DEFAULT '*',
	USER_SSN VARCHAR(13),
	PHONE VARCHAR(13),
	REG_REQ_USER_NAME VARCHAR(10),
	TITLE_NAME VARCHAR(10),
	EMP_NO VARCHAR(10),
	BRANCH_NO VARCHAR(10),
	BIZ_AUTH_CODE VARCHAR(100),
	LOGIN_FAIL_COUNT DECIMAL(1,0) DEFAULT 0,
	LAST_PWD_UPDATE_DTIME VARCHAR(14),
	DEFAULT_PROJECT_ID VARCHAR(20),
	PA_USER VARCHAR(128),
	PRE_PA_USER VARCHAR(128),
	PA_USER_SALT VARCHAR(50),
	PRE_PA_USER_SALT VARCHAR(50),
	FINAL_APPROVAL_STATE VARCHAR(1),
	FINAL_APPROVAL_DTIME VARCHAR(14),
	FINAL_APPROVAL_USER_ID VARCHAR(20),
	FINAL_APPROVAL_USER_NAME VARCHAR(50),
	PASSWD VARCHAR(100),
	CONSTRAINT PK_FWK_USER PRIMARY KEY (USER_ID),
	CONSTRAINT SYS_C0012770 CHECK (USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0012771 CHECK (USER_NAME IS NOT NULL),
	CONSTRAINT SYS_C0012772 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0012773 CHECK (LAST_UPDATE_USER_ID IS NOT NULL)
);
