-- FWK_PROPERTY_HISTORY definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_PROPERTY_HISTORY;

CREATE TABLE FWK_PROPERTY_HISTORY (
	PROPERTY_GROUP_ID VARCHAR(20),
	PROPERTY_ID VARCHAR(100),
	VERSION DECIMAL(5,0),
	PROPERTY_NAME VARCHAR(100),
	PROPERTY_DESC VARCHAR(300),
	DATA_TYPE VARCHAR(1),
	VALID_DATA VARCHAR(1000),
	DEFAULT_VALUE VARCHAR(1000),
	REASON VARCHAR(2000),
	LAST_UPDATE_USER_ID VARCHAR(20),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	CONSTRAINT PK_FWK_PROPERTY_HISTORY PRIMARY KEY (PROPERTY_GROUP_ID,PROPERTY_ID,VERSION),
	CONSTRAINT SYS_C0012373 CHECK (PROPERTY_GROUP_ID IS NOT NULL),
	CONSTRAINT SYS_C0012374 CHECK (PROPERTY_ID IS NOT NULL),
	CONSTRAINT SYS_C0012375 CHECK (VERSION IS NOT NULL),
	CONSTRAINT SYS_C0012376 CHECK (PROPERTY_NAME IS NOT NULL),
	CONSTRAINT SYS_C0012377 CHECK (PROPERTY_DESC IS NOT NULL),
	CONSTRAINT SYS_C0012378 CHECK (LAST_UPDATE_USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0012379 CHECK (LAST_UPDATE_DTIME IS NOT NULL)
);
