-- FWK_TRANSPORT definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_TRANSPORT;

CREATE TABLE FWK_TRANSPORT (
	ORG_ID VARCHAR(10),
	TRX_TYPE VARCHAR(1),
	IO_TYPE VARCHAR(1),
	REQ_RES_TYPE VARCHAR(1),
	GW_ID VARCHAR(20),
	CONSTRAINT SYS_C0012721 CHECK (ORG_ID IS NOT NULL),
	CONSTRAINT SYS_C0012722 CHECK (TRX_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0012723 CHECK (IO_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0012724 CHECK (REQ_RES_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0012725 PRIMARY KEY (ORG_ID,TRX_TYPE,IO_TYPE,REQ_RES_TYPE)
);
