-- FWK_TRX_MESSAGE definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_TRX_MESSAGE;

CREATE TABLE FWK_TRX_MESSAGE (
	TRX_ID VARCHAR(40),
	ORG_ID VARCHAR(10),
	IO_TYPE VARCHAR(1),
	MESSAGE_ID VARCHAR(50),
	STD_MESSAGE_ID VARCHAR(50),
	RES_MESSAGE_ID VARCHAR(50),
	STD_RES_MESSAGE_ID VARCHAR(50),
	PROXY_RES_YN VARCHAR(1) DEFAULT 'Y',
	PROXY_RES_DATA VARBINARY(2000),
	EXECUTE_SEQ DECIMAL(3,0) DEFAULT 1,
	PROXY_RES_TYPE VARCHAR(1) DEFAULT 'M',
	HEX_LOG_YN VARCHAR(1),
	MULTI_RES_YN VARCHAR(1),
	RES_TYPE_FIELD_ID VARCHAR(50),
	MULTI_RES_TYPE VARCHAR(1) DEFAULT '1',
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	TIMEOUT_SEC DECIMAL(3,0) DEFAULT 210 ,
	LEGACY_MESSAGE_ID VARCHAR(20),
	TARGET_SERVICE_URI VARCHAR(200),
	CONSTRAINT PK_FWK_BIZ_MESSAGE PRIMARY KEY (TRX_ID,ORG_ID,IO_TYPE),
	CONSTRAINT SYS_C0012748 CHECK (TRX_ID IS NOT NULL),
	CONSTRAINT SYS_C0012749 CHECK (ORG_ID IS NOT NULL),
	CONSTRAINT SYS_C0012750 CHECK (IO_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0012751 CHECK (MESSAGE_ID IS NOT NULL),
	CONSTRAINT SYS_C0012752 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0012753 CHECK (TIMEOUT_SEC IS NOT NULL)
);
