-- FWK_BATCH_APP definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_BATCH_APP;

CREATE TABLE FWK_BATCH_APP (
	BATCH_APP_ID VARCHAR(50),
	BATCH_APP_NAME VARCHAR(50),
	BATCH_APP_FILE_NAME VARCHAR(200),
	BATCH_APP_DESC VARCHAR(200),
	PRE_BATCH_APP_ID VARCHAR(50),
	BATCH_CYCLE VARCHAR(1),
	CRON_TEXT VARCHAR(20),
	RETRYABLE_YN VARCHAR(1) DEFAULT 'Y' ,
	PER_WAS_YN VARCHAR(1) DEFAULT 'Y' ,
	IMPORTANT_TYPE VARCHAR(1),
	PROPERTIES VARCHAR(500),
	TRX_ID VARCHAR(20),
	ORG_ID VARCHAR(10),
	IO_TYPE VARCHAR(1),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	CONSTRAINT PK_FWK_BATCH_APP PRIMARY KEY (BATCH_APP_ID),
	CONSTRAINT SYS_C0011090 CHECK (BATCH_APP_ID IS NOT NULL),
	CONSTRAINT SYS_C0011091 CHECK (BATCH_APP_FILE_NAME IS NOT NULL),
	CONSTRAINT SYS_C0011092 CHECK (BATCH_CYCLE IS NOT NULL),
	CONSTRAINT SYS_C0011093 CHECK (RETRYABLE_YN IS NOT NULL),
	CONSTRAINT SYS_C0011094 CHECK (PER_WAS_YN IS NOT NULL),
	CONSTRAINT SYS_C0011095 CHECK (IMPORTANT_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0011096 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0011097 CHECK (LAST_UPDATE_USER_ID IS NOT NULL)
);
