-- FWK_ERROR_HANDLE_HIS definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_ERROR_HANDLE_HIS;

CREATE TABLE FWK_ERROR_HANDLE_HIS (
	ERROR_CODE VARCHAR(40),
	HANDLE_APP_ID VARCHAR(50),
	ERROR_SER_NO VARCHAR(28),
	ERROR_HANDLE_DTIME VARCHAR(14),
	ERROR_HANDLE_RT_CODE VARCHAR(8),
	ERROR_HANDLE_TEXT VARCHAR(2000),
	CONSTRAINT PK_FWK_ERROR_HANDLE_HIS PRIMARY KEY (ERROR_CODE,HANDLE_APP_ID,ERROR_SER_NO),
	CONSTRAINT SYS_C0011314 CHECK (ERROR_CODE IS NOT NULL),
	CONSTRAINT SYS_C0011315 CHECK (HANDLE_APP_ID IS NOT NULL),
	CONSTRAINT SYS_C0011316 CHECK (ERROR_SER_NO IS NOT NULL),
	CONSTRAINT SYS_C0011317 CHECK (ERROR_HANDLE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0011318 CHECK (ERROR_HANDLE_RT_CODE IS NOT NULL)
);
