-- FWK_BOARD_CATEGORY definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_BOARD_CATEGORY;

CREATE TABLE FWK_BOARD_CATEGORY (
	BOARD_ID VARCHAR(20),
	CATEGORY_SEQ VARCHAR(10),
	CATEGORY_NAME VARCHAR(50),
	CONSTRAINT PK_FWK_BOARD_CATEGORY PRIMARY KEY (BOARD_ID,CATEGORY_SEQ),
	CONSTRAINT SYS_C0011133 CHECK (BOARD_ID IS NOT NULL),
	CONSTRAINT SYS_C0011134 CHECK (CATEGORY_SEQ IS NOT NULL),
	CONSTRAINT SYS_C0011135 CHECK (CATEGORY_NAME IS NOT NULL)
);
