-- FWK_WAS_INSTANCE definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_WAS_INSTANCE;

CREATE TABLE FWK_WAS_INSTANCE (
	INSTANCE_ID VARCHAR(4),
	INSTANCE_NAME VARCHAR(50),
	INSTANCE_DESC VARCHAR(200),
	WAS_CONFIG_ID VARCHAR(10),
	INSTANCE_TYPE VARCHAR(1),
	IP VARCHAR(15),
	PORT VARCHAR(5),
	OPER_MODE_TYPE VARCHAR(1),
	CONSTRAINT PK_FWK_WAS_INSTANCE PRIMARY KEY (INSTANCE_ID),
	CONSTRAINT SYS_C0012806 CHECK (INSTANCE_ID IS NOT NULL)
);
