-- FWK_PROPERTY definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_PROPERTY;

CREATE TABLE FWK_PROPERTY (
	PROPERTY_GROUP_ID VARCHAR(20),
	PROPERTY_ID VARCHAR(100),
	PROPERTY_NAME VARCHAR(100),
	PROPERTY_DESC VARCHAR(300),
	DATA_TYPE VARCHAR(1),
	VALID_DATA VARCHAR(1000),
	DEFAULT_VALUE VARCHAR(1000),
	LAST_UPDATE_USER_ID VARCHAR(20),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	CUR_VERSION BIGINT,
	FINAL_APPROVAL_STATE VARCHAR(1),
	FINAL_APPROVAL_DTIME VARCHAR(14),
	FINAL_APPROVAL_USER_ID VARCHAR(20),
	FINAL_APPROVAL_USER_NAME VARCHAR(50),
	CONSTRAINT PK_FWK_PROPERTY PRIMARY KEY (PROPERTY_GROUP_ID,PROPERTY_ID),
	CONSTRAINT SYS_C0012366 CHECK (PROPERTY_GROUP_ID IS NOT NULL),
	CONSTRAINT SYS_C0012367 CHECK (PROPERTY_ID IS NOT NULL),
	CONSTRAINT SYS_C0012368 CHECK (PROPERTY_NAME IS NOT NULL),
	CONSTRAINT SYS_C0012369 CHECK (PROPERTY_DESC IS NOT NULL),
	CONSTRAINT SYS_C0012370 CHECK (LAST_UPDATE_USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0012371 CHECK (LAST_UPDATE_DTIME IS NOT NULL)
);
