-- FWK_ERROR_DESC definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_ERROR_DESC;

CREATE TABLE FWK_ERROR_DESC (
	ERROR_CODE VARCHAR(40),
	LOCALE_CODE VARCHAR(5),
	ERROR_TITLE VARCHAR(200),
	PB_ERROR_TITLE VARCHAR(400),
	ETC_ERROR_TITLE VARCHAR(400),
	ERROR_CAUSE_DESC VARCHAR(1600),
	ERROR_GUIDE_DESC VARCHAR(1600),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	HELP_PAGE_URL VARCHAR(200),
	IBS_ERROR_GUIDE_DESC VARCHAR(1600),
	CMS_ERROR_GUIDE_DESC VARCHAR(1600),
	ETC_ERROR_GUIDE_DESC VARCHAR(1600),
	FINAL_APPROVAL_STATE VARCHAR(1),
	FINAL_APPROVAL_DTIME VARCHAR(14),
	FINAL_APPROVAL_USER_ID VARCHAR(20),
	FINAL_APPROVAL_USER_NAME VARCHAR(50),
	CONSTRAINT PK_FWK_ERROR_DESC PRIMARY KEY (ERROR_CODE,LOCALE_CODE),
	CONSTRAINT SYS_C0011621 CHECK (ERROR_CODE IS NOT NULL),
	CONSTRAINT SYS_C0011622 CHECK (LOCALE_CODE IS NOT NULL),
	CONSTRAINT SYS_C0011623 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0011624 CHECK (LAST_UPDATE_USER_ID IS NOT NULL)
);
