-- FWK_TRANS_DATA_TIMES definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_TRANS_DATA_TIMES;

CREATE TABLE FWK_TRANS_DATA_TIMES (
	TRAN_SEQ VARCHAR(14),
	TRAN_REASON VARCHAR(100),
	TRAN_RESULT VARCHAR(1),
	TRAN_TIME VARCHAR(14),
	USER_ID VARCHAR(20),
	CONSTRAINT PK_FWK_TRANS_DATA_TIMES PRIMARY KEY (TRAN_SEQ),
	CONSTRAINT SYS_C0012732 CHECK (TRAN_SEQ IS NOT NULL),
	CONSTRAINT SYS_C0012733 CHECK (TRAN_RESULT IS NOT NULL),
	CONSTRAINT SYS_C0012734 CHECK (TRAN_TIME IS NOT NULL),
	CONSTRAINT SYS_C0012735 CHECK (USER_ID IS NOT NULL)
);
