-- FWK_BOARD_AUTH definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_BOARD_AUTH;

CREATE TABLE FWK_BOARD_AUTH (
	USER_ID VARCHAR(20),
	BOARD_ID VARCHAR(20),
	AUTH_CODE VARCHAR(1),
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	CONSTRAINT PK_FWK_BOARD_AUTH PRIMARY KEY (USER_ID,BOARD_ID),
	CONSTRAINT SYS_C0011127 CHECK (USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0011128 CHECK (BOARD_ID IS NOT NULL),
	CONSTRAINT SYS_C0011129 CHECK (AUTH_CODE IS NOT NULL),
	CONSTRAINT SYS_C0011130 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0011131 CHECK (LAST_UPDATE_USER_ID IS NOT NULL)
);
