-- FWK_WAS_LISTENER definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_WAS_LISTENER;

CREATE TABLE FWK_WAS_LISTENER (
	INSTANCE_ID VARCHAR(4),
	GW_ID VARCHAR(20),
	SYSTEM_ID VARCHAR(20),
	WAS_INSTANCE_STATUS VARCHAR(5),
	ACTIVE_COUNT_IDLE DECIMAL(3,0),
	LAST_UPDATE_DTIME VARCHAR(20),
	CONSTRAINT PK_WAS_LISTENER PRIMARY KEY (INSTANCE_ID,GW_ID,SYSTEM_ID),
	CONSTRAINT SYS_C0012808 CHECK (INSTANCE_ID IS NOT NULL),
	CONSTRAINT SYS_C0012809 CHECK (GW_ID IS NOT NULL),
	CONSTRAINT SYS_C0012810 CHECK (SYSTEM_ID IS NOT NULL)
);
