-- FWK_ARTICLE definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_ARTICLE;

CREATE TABLE FWK_ARTICLE (
	ARTICLE_SEQ BIGINT,
	BOARD_ID VARCHAR(20),
	CATEGORY_SEQ VARCHAR(20),
	TOP_YN VARCHAR(1),
	REF_ARTICLE_SEQ BIGINT,
	`POSITION` BIGINT,
	STEP BIGINT,
	TITLE VARCHAR(500),
	WRITER_ID VARCHAR(20),
	WRITER_NAME VARCHAR(50),
	READ_CNT BIGINT,
	ATTATCH_FILE_PATH_1 VARCHAR(500),
	DOWNLOAD_CNT_1 BIGINT,
	ATTATCH_FILE_PATH_2 VARCHAR(500),
	DOWNLOAD_CNT_2 BIGINT,
	ATTATCH_FILE_PATH_3 VARCHAR(500),
	DOWNLOAD_CNT_3 BIGINT,
	REGIST_DTIME VARCHAR(14),
	LAST_UPDATE_DTIME VARCHAR(14),
	LAST_UPDATE_USER_ID VARCHAR(20),
	CONTENT TEXT,
	CONSTRAINT SYS_C0012928 CHECK (ARTICLE_SEQ IS NOT NULL),
	CONSTRAINT SYS_C0012929 CHECK (`POSITION` IS NOT NULL),
	CONSTRAINT SYS_C0012930 CHECK (STEP IS NOT NULL),
	CONSTRAINT SYS_C0012931 CHECK (READ_CNT IS NOT NULL),
	CONSTRAINT SYS_C0013663 CHECK (BOARD_ID IS NOT NULL),
	CONSTRAINT SYS_C0013664 CHECK (TOP_YN IS NOT NULL),
	CONSTRAINT SYS_C0013665 CHECK (TITLE IS NOT NULL),
	CONSTRAINT SYS_C0013666 CHECK (WRITER_ID IS NOT NULL),
	CONSTRAINT SYS_C0013667 CHECK (WRITER_NAME IS NOT NULL),
	CONSTRAINT SYS_C0013668 CHECK (LAST_UPDATE_USER_ID IS NOT NULL),
	CONSTRAINT SYS_C0013669 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0013670 CHECK (REGIST_DTIME IS NOT NULL)
);