-- FWK_TRX_MESSAGE_HISTORY definition

-- Converted from Oracle DDL for MySQL (Testcontainer)


-- Drop table

-- DROP TABLE FWK_TRX_MESSAGE_HISTORY;

CREATE TABLE FWK_TRX_MESSAGE_HISTORY (
	TRX_ID VARCHAR(40),
	ORG_ID VARCHAR(10),
	IO_TYPE VARCHAR(1),
	MESSAGE_ID VARCHAR(50),
	STD_MESSAGE_ID VARCHAR(50),
	RES_MESSAGE_ID VARCHAR(50),
	STD_RES_MESSAGE_ID VARCHAR(50),
	PROXY_RES_YN VARCHAR(1) DEFAULT 'Y',
	PROXY_RES_DATA VARBINARY(2000),
	EXECUTE_SEQ DECIMAL(3,0) DEFAULT 1,
	PROXY_RES_TYPE VARCHAR(1) DEFAULT 'M',
	HEX_LOG_YN VARCHAR(1),
	MULTI_RES_YN VARCHAR(1),
	RES_TYPE_FIELD_ID VARCHAR(50),
	MULTI_RES_TYPE VARCHAR(1) DEFAULT '1',
	LAST_UPDATE_DTIME VARCHAR(14) DEFAULT NULL ,
	LAST_UPDATE_USER_ID VARCHAR(20),
	TIMEOUT_SEC DECIMAL(3,0) DEFAULT 210 ,
	LEGACY_MESSAGE_ID VARCHAR(20),
	VERSION DECIMAL(3,0),
	CONSTRAINT PK_FWK_TRX_MESSAGE_HISTORY PRIMARY KEY (TRX_ID,ORG_ID,IO_TYPE,VERSION),
	CONSTRAINT SYS_C0012755 CHECK (TRX_ID IS NOT NULL),
	CONSTRAINT SYS_C0012756 CHECK (ORG_ID IS NOT NULL),
	CONSTRAINT SYS_C0012757 CHECK (IO_TYPE IS NOT NULL),
	CONSTRAINT SYS_C0012758 CHECK (MESSAGE_ID IS NOT NULL),
	CONSTRAINT SYS_C0012759 CHECK (LAST_UPDATE_DTIME IS NOT NULL),
	CONSTRAINT SYS_C0012760 CHECK (TIMEOUT_SEC IS NOT NULL),
	CONSTRAINT SYS_C0012761 CHECK (VERSION IS NOT NULL)
);
