import globals from 'globals';

export default [{
  files: ['../resources/static/js/**/*.js'],
  languageOptions: {
    globals: {
      ...globals.browser,
      SpiderConfig: 'readonly',
      SpiderToast: 'readonly',
      SpiderDialog: 'readonly',
      SpiderDateDefaults: 'readonly',
      SpiderExcel: 'readonly',
      SpiderPrint: 'readonly',
      SpiderI18n: 'readonly',
      SpiderValidation: 'readonly',
      SpiderPermission: 'readonly',
      SpiderTheme: 'readonly',
      SpiderDataTable: 'readonly',
      SpiderPagination: 'readonly',
      SpiderSearchPanel: 'readonly',
      SpiderToolbar: 'readonly',
      SpiderDetailPanel: 'readonly',
      SpiderTree: 'readonly',
      qs: 'readonly',
      qsa: 'readonly',
      delegate: 'readonly',
      api: 'readonly',
    },
  },
  rules: {
    'no-var':              'error',
    'no-implicit-globals': 'error',
    'eqeqeq':             'error',
    'prefer-const':        'warn',
    'no-restricted-globals': ['error',
      { name: '$', message: 'jQuery is not available. Use qs() / qsa() from spider-core.js.' },
      { name: 'jQuery', message: 'jQuery is not available. Use native APIs.' },
    ],
    'no-restricted-syntax': ['error',
      { selector: "CallExpression[callee.name='$']",
        message: 'jQuery is not available. Use qs() / qsa() from spider-core.js.' },
      { selector: "CallExpression[callee.object.name='$']",
        message: 'jQuery is not available. Use native fetch / addEventListener.' },
    ],
  },
}];
